version: '3.3'
services:
  client:
    environment:
      - GET_HOSTS_FROM=dns
    image: "scaleoutsystems/casa-client:latest"
    build:
      context: .
    working_dir: /app
    command: /bin/bash -c "fedn run client -in fedn-network.yaml"
    volumes:
      - ./casa1/c0:/app/data

